### ISSUE TITLE
question about the Pre-processing

### ISSUE THREAD

**Issue by Robertwyq** [google/dynamic-video-depth#1]
Can you provide the code for preprocessing part? I wonder for dynamic video, how to get accurate camera pose and K? I see you use DAVIS for example, I want to know how to deal with other videos in this dataset.

**Comment by ztzhang** [comment]
Hi, 

Most of the preprocessing was done using internal tools at google, but as a rule of thumb, it usually works well to use mask-rcnn for segmenting the foreground object, and then run colmap with the segmented masks.

**Comment by Robertwyq** [comment]
Thank you for your reply. I noticed that you mentioned using ORBSLAM2 and COLMAP to produce camera pose estimates in your paper. I wonder whether the above method can be successful without mask or manual selection for only a small number of foreground moving objects.

**Comment by ztzhang** [comment]
orbslam typically works with reasonable dynamic scenes but it does require camera intrinsics. I think you can assume a reasonable focal length, and pass the keypoints and camera calibrations to colmap for further optimizations.

**Comment by Robertwyq** [comment]
Thank you very much😁

**Comment by Robertwyq** [comment]
Thank you for your reply. When I tested some videos of road scenes, I found that it would blur a lot of distant details, but I found that there were still a lot of details in the initial estimation of the network. I want to know if there are any suggestions on network parameter adjustment. I think it is mainly due to the influence of flow information. Can you give me some suggestions? 
![image](https://user-images.githubusercontent.com/39329846/131244124-ee25ef51-6e2f-450a-851a-f339665efb9a.png)
![image](https://user-images.githubusercontent.com/39329846/131244130-b2b8e166-115a-406b-b50b-c4e509699034.png)

**Comment by Robertwyq** [comment]
Thank you for your reply.
